#!/bin/bash
#SBATCH -J stdio_exdyna
#SBATCH -p cas_v100_4
#SBATCH -N 4
#SBATCH -n 4
#SBATCH -o %x.o%j
#SBATCH -e %x.e%j
#SBATCH --time 12:00:00
#SBATCH --gres=gpu:1
#SBATCH --comment etc     # See Application SBATCH options name table's

module purge
module load python/3.7.1
source activate exdyna

nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) )
nodes_array=($nodes)
head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)
master_port="$((RANDOM%55535+10000))"

echo Node IP: $head_node_ip
echo Port: $master_port
export LOGLEVEL=INFO

hostip=$head_node_ip port=$master_port mpirun -np 4 run.sh

#hostip=$head_node_ip port=$master_port srun run.sh
#srun torchrun --rdzv_id $RANDOM --rdzv_backend=distributed_backend --rdzv_endpoint=$head_node_ip:29500 --nnodes=2 --nproc_per_node=1 a.py
